# Librería Numpy

In [1]:
import numpy as np

In [14]:
lista = [25, 12, 15, 66, 12.5]
vector = np.array(lista)
print(lista)
print(vector)
print(3*vector)

[25, 12, 15, 66, 12.5]
[25.  12.  15.  66.  12.5]
[ 75.   36.   45.  198.   37.5]


In [10]:
np?

In [12]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [13]:
lista = [25, 12, 15, 66, 12.5]
print(lista*3)
type(lista)

[25, 12, 15, 66, 12.5, 25, 12, 15, 66, 12.5, 25, 12, 15, 66, 12.5]


list

In [15]:
lista = [25, 12, 15, 66, 12.5]
vector = np.array(lista)
vector.shape

(5,)

In [16]:
len(vector)

5

In [18]:
# Diferecia entre lista y vector
print(lista*5)
print(vector*5)

[25, 12, 15, 66, 12.5, 25, 12, 15, 66, 12.5, 25, 12, 15, 66, 12.5, 25, 12, 15, 66, 12.5, 25, 12, 15, 66, 12.5]
[125.   60.   75.  330.   62.5]


In [73]:
a=[1,2,3,4,5]
for i in a:
    print(a[i])

2
3
4
5


IndexError: list index out of range

### Tuplas (). Inmutables

In [26]:
words = ("spam", "eggs", "sausages")
words[1]="salsa"

TypeError: 'tuple' object does not support item assignment

### Diccionarios {} 

In [25]:
# Claves y valores de las claves
ages = {"Dave":24, "Mary":42, "Jhon":52}
print(ages["Dave"])
print(ages["Mary"])

24
42


In [32]:
cars_colors = {"BMW": "Blue",  "VOLVO" : "Red"}
print(cars_colors["VOLVO"])

Red


In [40]:
primary = {
    "red" : [255,0,0],
    "green" : [0,255,0],
    "blue" : [0,0,255],
}

print(primary["red"])
print(primary["yellow"])

[255, 0, 0]


KeyError: 'yellow'

In [41]:
test = {}
print(test[0])

KeyError: 0

In [45]:
squares = {1:1, 2:4, 3:"error", 4:16}
squares[8]=64
squares[5]="Hi!"
squares[3]=9
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 8: 64, 5: 'Hi!'}


In [65]:
nums = {
    1:"one",
    2:"two",
    3:"three",
}

print(1 in nums)
print(4 not in nums)
print(5 in nums)

True
True
False


## Operaciones

In [68]:
import numpy as np

In [69]:
lista = [25, 12, 15, 66, 12.5]
vector = np.array(lista)
print("- vector original")
print(vector)     

- vector original
[25.  12.  15.  66.  12.5]


In [61]:
print("- sumarle 1 a cada elemento del vector:")
print(vector+1)
print("- multiplicar por 5 cada elemento del vector:")
print(vector*5)

- sumarle 1 a cada elemento del vector:
[26.  13.  16.  67.  13.5]
- multiplicar por 5 cada elemento del vector:
[125.   60.   75.  330.   62.5]


In [62]:
print("- suma de los elementos:")
print(np.sum(vector))

- suma de los elementos:
130.5


In [63]:
print("- promedio (media) de los elementos:")
print(np.mean(vector)) # 

- promedio (media) de los elementos:
26.1


In [70]:
print("- el vector sumado a si mismo:")
print(vector+vector)
print("- suma de vectores vector1 y vector2 (mismo tamaño):")
vector2=np.array([11,55,1.2,7.4,-8])
print(vector+vector2)

- el vector sumado a si mismo:
[ 50.  24.  30. 132.  25.]
- suma de vectores vector1 y vector2 (mismo tamaño):
[36.  67.  16.2 73.4  4.5]


## Índices y Slices

SyntaxError: illegal target for annotation (<ipython-input-72-404a35849a23>, line 1)

In [77]:
square = [0,1,4,9,16,25,36,49,64,81]
print(square[::2])
print(square[2:8:3])
print(square[-1])

[0, 4, 16, 36, 64]
[4, 25]
81


### Matrices

In [81]:
lista_de_listas = [ [1,-4],
                    [12, 3],
                    [7.2, 5] ]

matriz = np.array(lista_de_listas)
print(matriz)
type(lista_de_listas)
type(matriz)

[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]


numpy.ndarray

In [2]:
import numpy as np
A=np.array([[1,4], [-2,6], [10,4]])

In [3]:
# Producto Hadamard
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[5, 6],
       [7, 8]])